swagger: '2.0'
info:
    title: Admin API
    description: API for managing admins
    version: 1.0.0
basePath: /api
tags:
    - name: Admins
      description: Operations related to admins
securityDefinitions:
    BearerAuth:
        type: apiKey
        name: Authorization
        in: header
paths:
    /admins:
        post:
            summary: Register a new admin
            tags:
                - Admins
            security:
                - BearerAuth: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    example: user@example.com
            responses:
                '201':
                    description: Admin registered successfully. A refresh token is set in an HTTP-only cookie.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    user:
                                        $ref: '#/definitions/User'
                '400':
                    description: Bad Request
                '409':
                    description: Conflict - Email already exists

        get:
            summary: Get all admins
            tags: [Admins]
            security:
                - BearerAuth: []
            responses:
                '200':
                    description: A list of all admins
                '403':
                    description: Forbidden - Only admins can access this endpoint
    /admins/{id}:
        delete:
            summary: Delete a admin by ID
            tags: [Admins]
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      type: string
                  description: ID of the admin to delete
            security:
                - BearerAuth: []
            responses:
                '200':
                    description: Admin deleted successfully
                '403':
                    description: Forbidden - Only admins can delete admins
                '404':
                    description: Not Found - Admin not found
definitions:
    schemas:
        User:
            type: object
            properties:
                id:
                    type: string
                    example: 60d0fe4f5311236168a109ca
                email:
                    type: string
                    example: user@example.com
                role:
                    type: string
                    enum: [admin, teacher]
                    example: teacher
