swagger: '2.0'
info:
    title: Teachers API
    description: API documentation for managing teachers
    version: 1.0.0
basePath: /api
tags:
    - name: Teachers
      description: Operations related to teachers
paths:
    /teachers:
        get:
            summary: Retrieve all teachers
            tags:
                - Teachers
            responses:
                '200':
                    description: Successful request. Returns a list of teachers.
                '500':
                    description: Server error. Failed to retrieve teachers.
        post:
            summary: Add a teacher
            tags:
                - Teachers
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/definitions/TeacherInput'
            responses:
                '201':
                    description: Successful request. Adds a teacher.
                '400':
                    description: Bad request. Validation error.
                '401':
                    description: Unauthorized - Token missing
                '403':
                    description: Forbidden - Invalid refresh token
                '500':
                    description: Server error. Failed to add teacher.
    /teachers/{id}:
        get:
            summary: Retrieve a teacher by ID
            tags:
                - Teachers
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      type: string
                  description: ID of the teacher to retrieve
            responses:
                '200':
                    description: Successful request. Returns the specified teacher.
                '401':
                    description: Unauthorized - Token missing
                '403':
                    description: Forbidden - Invalid refresh token
                '404':
                    description: Teacher not found.
                '500':
                    description: Server error. Failed to retrieve teacher.
        put:
            summary: Update a teacher by ID
            tags:
                - Teachers
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      type: string
                  description: ID of the teacher to update
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/definitions/TeacherInput'
            responses:
                '200':
                    description: Successful request. Returns the updated teacher.
                '400':
                    description: Client error. Failed to update teacher.
                '401':
                    description: Unauthorized - Token missing
                '403':
                    description: Forbidden - Invalid refresh token
                '404':
                    description: Teacher not found.
        patch:
            summary: Partially update a teacher by ID
            tags:
                - Teachers
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      type: string
                  description: ID of the teacher to update
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/definitions/TeacherInput'
            responses:
                '200':
                    description: Successful request. Returns the updated teacher.
                '400':
                    description: Client error. Failed to update teacher.
                '401':
                    description: Unauthorized - Token missing
                '403':
                    description: Forbidden - Invalid refresh token
                '404':
                    description: Teacher not found.
        delete:
            summary: Delete a teacher by ID
            tags:
                - Teachers
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      type: string
                  description: ID of the teacher to delete
            responses:
                '200':
                    description: Successful request. Teacher deleted.
                '401':
                    description: Unauthorized - Token missing
                '403':
                    description: Forbidden - Invalid refresh token
                '404':
                    description: Teacher not found.
                '500':
                    description: Server error. Failed to delete teacher.
    /teachers/current:
        get:
            summary: Retrieve the teacher details of the currently authenticated user
            tags:
                - Teachers
            responses:
                '200':
                    description: Successful request. Returns the details of the currently authenticated teacher.
                    schema:
                        $ref: '#/definitions/Teacher'
                '401':
                    description: Unauthorized - Token missing
                '403':
                    description: Forbidden - Invalid refresh token
                '500':
                    description: Server error. Failed to retrieve teacher details.
definitions:
    TeacherInput:
        type: object
        properties:
            lastName:
                type: string
                description: Teacher's last name
            firstName:
                type: string
                description: Teacher's first name
            patronymic:
                type: string
                description: Teacher's patronymic
            phone:
                type: string
                description: Teacher's phone number
            experience:
                type: number
                description: Years of experience
            subjects:
                type: array
                items:
                    type: string
                    description: List of subject IDs
            email:
                type: string
                description: Teacher's email
        required:
            - lastName
            - firstName
            - patronymic
            - phone
            - email
            - subjects
            - experience

    Teacher:
        allOf:
            - $ref: '#/definitions/TeacherInput'
            - type: object
              properties:
                  _id:
                      type: string
                      description: Teacher ID
              required:
                  - _id
