swagger: '2.0'
info:
    title: User API
    description: API for managing admins
    version: 1.0.0
basePath: /api
tags:
    - name: Admins
      description: Operations related to admins
securityDefinitions:
    BearerAuth:
        type: apiKey
        name: Authorization
        in: header
paths:
    /admins:
        get:
            summary: Get all admins
            tags: [Admins]
            security:
                - BearerAuth: []
            responses:
                '200':
                    description: A list of all admins
                '403':
                    description: Forbidden - Only admins can access this endpoint
    /admins/{id}:
        delete:
            summary: Delete a user by ID
            tags: [Admins]
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      type: string
                  description: ID of the user to delete
            security:
                - BearerAuth: []
            responses:
                '200':
                    description: User deleted successfully
                '403':
                    description: Forbidden - Only admins can delete admins
                '404':
                    description: Not Found - User not found
definitions:
    schemas:
        User:
            type: object
            properties:
                id:
                    type: string
                    example: 60d0fe4f5311236168a109ca
                email:
                    type: string
                    example: user@example.com
                role:
                    type: string
                    enum: [admin, teacher]
                    example: teacher
                refrshToken:
                    type: string
                    exampe: 'sdfsd7823khsgdf3mnbsdmfhgsiu2386jhsdf'
